### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#1]
* 建议添加对 Head Database 头颅的支持
* 建议加入自定义菜单路径的功能
* 建议添加除箱子页面的菜单（例如工作台、熔炉、漏斗等可交互容器）
* 菜单中的优先级可能与Shape存在一定的局限性（例如：菜单不能在优先级中自定义物品的slot）
* 建议添加自动排列物品（在指定的区域中，对在线玩家，进行排列。其中，排列出的玩家，都解析* 各自的变量），这样就能做传送玩家菜单、管理员菜单、查房菜单、经济管理菜单等。

**Comment by Arasple** [comment]
1. √
2. √
4. √

3, 5 后续会跟进支持
