### ISSUE TITLE
菜单显示条件BUG

### ISSUE THREAD

**Issue by benr233** [Arasple/TrMenu#10]
我在使用trmenu的过程中遇到了一个问题，我给我的菜单添加了变量判断条件，未满足条件的玩家会显示锁定，满足条件的玩家会显示副本信息，但是我发现未满足条件的玩家打开菜单后显示锁定中，等满足条件的玩家打开菜单后，未满足条件的玩家的菜单也变成副本信息了。
操作步骤：玩家1打开菜单（未满足条件）不关闭菜单不动，物品显示锁定状态，玩家2打开菜单（满足条件）此时显示副本信息的同时，玩家1的菜单也跟随刷新成副本信息

**Comment by Arasple** [comment]
Fixed.in v1.1

**Comment by Arasple** [comment]
Fixed in v1.12-R4
