### ISSUE TITLE
Pro版的一些功能建议

### ISSUE THREAD

**Issue by YsGqHY** [Arasple/TrMenu#101]
Pro现在写的怎么样了咱也不知道
但是在trmenu的基础上添加功能或修改功能的话
有几样功能我可以提供一定的建议，可仅做参考
1. 继承参数的{0}-{9}，可以继承更多的参数，并不局限于10个参数
2. 内置的自定义变量，在菜单内可以提供自定义Papi
3. 在条件/需求的表达式上有错误的游戏内报错，只显示给所有权限者，正常玩家显示其他的错误提示
4. 提供更多的TrUtils，例如点击对应消息执行的OPEN_URL或指令

**Comment by Arasple** [comment]
v2版本都会更新支持

1. 到时候使用 `%trmenu_args_10%` Papi变量调用10个以上的参数
4. 现在已有，可以使用 tellraw 动作或 TrUtils.getTellraw() 构建，后续文档会重写
