### ISSUE TITLE
JavaScript PlaceHolderAPI Bug

### ISSUE THREAD

**Issue by Tomi010817** [Arasple/TrMenu#102]
First off I want to say that I have been many hours making a deep investigation about this glitch to be able to bring you the most detailed report as possible so you could reproduce the glitch by your own and also to help you fix it more easily.

### _Description_
There is a glitch on TrMenu where apparently the placeholders randomly change of values for some miliseconds. This is commonly more easy to watch it happen when the placeholders are located either on button's titles or lores, but it is confirmed that it will also happen in everything related to the menu where those placeholders are located. (it currently happened to me in "shiny" option for buttons, on requirements for actions, titles, lores, and more).

The only way to reproduce this (at least from what I know), is by adding at least 1 JavaScript placeholder that has a value that changes constantly (like a countdown for example) on 2 different buttons. And it will glitch once every 5 to 20 seconds, and as I told before, it lasts some miliseconds (like a twinckle that shows other values that it should not be supposed to show on the placeholder).

The glitch comes to be very annoying for everything, and if you set requirements and use those placeholders alone on it, you will have the risk that someone will be able to bypass those requirements by fastly clicking the button until it catches a moment where the placeholder value glitches. And it is visually very annoying since it can ruin how your menu looks, for example:
- On a shop menu, a javascript placeholder that would show the cost of something, would turn "$500" when it is "false" and would turn "&a¡Unlocked!" when it is "true", but because of  another javascript placeholder that is on another button, acting like a countdown, the cost placeholder will twinckle sometimes showing other values like the 'time left' from the countdown of the other placeholder, or even it sometimes gets cursed showing the opposite value that it should be supposed to show.

**Are you sure that the glitch is caused by TrMenu? And how can you be 100% sure of it?**
Yes, I'm 100% sure that the glitch is caused by TrMenu, since I have tested those placeholders on the TabList, the Scoreboard, with placeholder parse command, and even with DeluxeMenus. The glitch would only happen on everything inside/related to the menu where those Javascript placeholders are in. Also the glitch isn't caused by your ping, or the server TPS, since I have also tested it on an empty localhost and also seems to be happening. 
I currently can't confirm if only the JavaScript placeholders are the cause of this glitch, but for the moment, they are the only ones that caused that to me.

### _Very Useful Information (Glitch demonstration)_
So I took the time to create a really simple and clear "Test" menu with TrMenu to show you off the glitch so that you could reproduce it by your own and see how annoying the glitch would actually be. I also even created an exact menu but with DeluxeMenus to demonstrate that it won't happen on DeluxeMenus. I also even added those placeholders on the scoreboard and **even** on the TabList, to also demonstrate you that it won't happen there, and the only place where it happens is inside of that menu from TrMenu.
### The Download is [>>Here<<](https://drive.google.com/file/d/1BZtv6glJtxuvD8DgzcZV1FNhZzVaFHgt/view?usp=sharing)
`(!) It has only been tested on MC 1.8.8 (!)`
**The download is a .zip file that contains the following plugins:**
- _TrMenu_ - **_Last Version_**
- _DeluxeMenus_ - **_1.8.0 for 1.8.8 compatibility_**
- _PlaceHolderAPI_ - **_Last Version_**
- _LuckPerms_ (to handle the needed temporary permissions for the javascript "countdown" placeholders. I created the javascript placeholder by editing the original one that would return empty when the countdown would end, and instead it would return a specified value) - **_Last Version_**
- _ProtocolLib_ - **_Last Version_**
- _TAB_ (to demonstrate that it won't happen on the TabList)
- _TitleManager_

**How to install:**
- The file is ready to be dropped and extracted on the empty plugins folder. And as I said above, your internet or the server TPS isn't the cause of the glitch, so it can be also reproduced through a localhost.

**How to open the menus:**
- _**/test-1**_ - It will open the menu done with TrMenu (where the glitch happens)
- _**/test-2**_ - It will open the menu done with DeluxeMenus (where the glitch won't happen)

**How to reproduce the Glitch:**
- So if you run the countdown of one of the 2 placeholders, the glitch will happen once every 5 to 20 seconds, lasting some miliseconds. The placeholder will twinckle showing the value of the other placeholder, or if the other placeholder is also running the countdown, then the first one may probably twinckle showing the countdown of the other placeholder.

### _Extra_
Also another thing that I would like to add (but maybe it should be on another github-issue), is that the "update" option for menus, won't work 100% accurately, that is because on the countdown placeholder, it sometimes get stucked for some miliseconds and after running again, it skips 2 seconds instead of just 1. All that happening when the update option was even set on "1" so it would reset every tick (20 times per second)... doesn't make sense. And it was also tested on an empty localhost. Deluxemenus maximum update-interval is 1 **_second_** (20 ticks) and it happens much less frequently than on TrMenu.

Hope it helped, and thanks to everyone that read it, regards ;)

**Comment by Tanguygab** [comment]
it's not only with Javascript placeholders, check my latest issue I made

**Comment by Tomi010817** [comment]
I've read that issue, and I'm sure that it also happens in there, but I'm not able to reproduce that since Idk how and in what circumstance will happen, that is why I said "I currently can't confirm if only the JavaScript placeholders are the cause of this glitch, but for the moment, they are the only ones that caused that to me."

**Comment by Tanguygab** [comment]
yeah I know, I couldn't reproduce it neither sometimes, and even in the same menu, it happens for some items and not for others. It's really strange. at some point I thought it was because of the permission check, but in the end it wasn't only that =/

**Comment by Tomi010817** [comment]
It was the same for me, about JavaScript placeholders, there are a lot of particular circumstances where it would also happen. Very weird and hope it can get fixed on the future xD

**Comment by Arasple** [comment]
Thank you for your report :)

**Comment by Tomi010817** [comment]
You are welcome Arasple-senpai. If you need me for further testing anything just dm me to my discord Tomi010817#8699
Very happy to see you back.

**Comment by Tomi010817** [comment]
@Arasple , I've tested the lastest version 1.22, and the bug still happens. I've got told through the discord server that it is also happening on v2

**Comment by Tanguygab** [comment]
the 1.22 update only removes the update checjer as said in the changelogs

**Comment by Tanguygab** [comment]
the bug will be fixed in v2

**Comment by Tomi010817** [comment]
Oof my bad xD 
I didn't even read changelogs from the excited I was to see if it was fixed or not in that version lol
