### ISSUE TITLE
5 Suggestions for TrMenu!

### ISSUE THREAD

**Issue by Tomi010817** [Arasple/TrMenu#103]
### Hello back!

So today I will bring 5 suggestions that will help TrMenu to become much more customizable and manipulable for us to enjoy at the maximum all the features that it already brings and even more.

### _First Suggestion_
- An optional way to be able to add buttons for each shape. But why? This could help a lot since we now use shapes to make all-in-one-menu, the letters and symbols run out when we make a large and big menu with lot of shapes and different buttons. So this is why I wanted to suggest a way to add buttons but for each shape, letting us repeat letters, numbers and symbols that we already used for other shapes, but with different settings. _This way we will be able to create a menu with no limitations on number of shapes and buttons._ 
**A template of how it could look if it is added:** [_**>Click here<**_](https://hastebin.com/oduhigibay.http)

### _Second Suggestion_
- Currently there is a "DELAY" action that stop all the following actions until the time defined next to "DELAY" ends. Problem is that the action "DELAY" won't listen to requirements, so it will run even if you set requirements on it. This is what this suggestion is about. It would be great to be able to add requirements on "DELAY" actions so if those requirements aren't met, then the whole action will be ignored. (for the moment you can use "<wait>" ActionOption but you would have to add it to each of the following actions where the DELAY action was)

### _Third Suggestion_
- When you set (for example) a sound as an action, with the clickType "ALL", then it will play the sound with all the functional keys (for MC related to GUIs). And some of them are the keys used to access the hotbar slots, but currently there isn't any clickType to set them specifically, in case you want to run actions whenever a player press a key from the hotbar slots. It would be such a cool feature to have that. It could look like: 
> HOTBAR_SLOT_1
> HOTBAR_SLOT_2
> HOTBAR_SLOT_3
> HOTBAR_SLOT_4
> HOTBAR_SLOT_5
> HOTBAR_SLOT_6
> HOTBAR_SLOT_7
> HOTBAR_SLOT_8
> HOTBAR_SLOT_9

### _Fourth Suggestion_
- When you set a "title" as an action, you have to set the input (for the title and subtitle) inside of angle brackets <>. That causes you to not be able to use the following symbols for the title action: `(` `<` `)` `>`. So my suggestion to fix that would be to let us optionally use quotes before the input so that is won't get confused with the symbols that are outside of it. It could look like this:
**`'title: <TITLE=":)"><SUBTITLE="This &6<>&f can also be used now!"><FADEIN=20><STAY=40><FADEOUT=20>'`**
And if you also want to use a quote inside, you would have to add it inside of the other quotes:
**`<TITLE=":)"">`**

### _Fifth Suggestion_
- Currently, the action `TELL` won't take/support the "\n" for skipping to the next line on chat. It would be good to bring support for using \n on TELL action since it would avoid the usage of multiple TELL actions (that will make it much more messier) and also help to make everything more fluid and organized.

Hope you like my suggestions! Thanks for reading, Regards.

**Comment by Tanguygab** [comment]
for the first suggestion, it is actually already possible with conditions and ve done it, you can just check for the shape with {shape}
for the second one, I just thought of something, instead of using <delay#><require:#>, maybe try <delay:#;require:#>? just thought of that at the moment x)
for the third suggestion: that could be done actually with javascript requirements, you add an action to the ALL type with a requirement with javascript that checks the selected hotbar slot (I have no idea on how to do it currently, I'll check later)
and for the fourth suggestion, maybe a \ is better to escape the characters as remiving the "" all around the <title> isn't really possible if you don't want to break the YAML format

**Comment by Tomi010817** [comment]
Thanks for reading, and for sharing you opinion Gab!
And yes, most of them are already possible to be done with more complex methods.
Most of the suggestions are intended to be made with the objective to make TrMenu much more organized, and way mooore comfortable to manage and edit.

**Comment by Arasple** [comment]
first suggestion probably not going to support
however, there will be a way to create unlimited icons in layouts

If an icon's id is a string, you can define it in a layout with `

```YAML
Layout:
  - '########`Close`'
  - '         '
  - ' *       '
  - '         '
  - '`Pre`########'
```

Other suggestions will all be supported in v2
