### ISSUE TITLE
[v2] Shapes and PlayerInventory

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#107]
On TrMenu v2, when you use the PlayerInventory and multiples Shapes, the items in the PlayerInventory will disappear.

This is what it should do (in my mind)...

This doesn't depend on shapes and will always be shown:
```yml
PlayerInventory:
  - '         '
  - '  `Pre` `Welcome` `Next`  '
  - '         '
  - '         '
```

And this depends on shapes, so if you are on the Shape 0, the first one will be displayed and if you switch to Shape 1, the second will, just like normal Shapes/Layout do
```yml
PlayerInventory:
  - - '         '
    - '  `Pre` `Welcome` `Next`  '
    - '         '
    - '         '
  - - '         '
    - '  `Pre` `Close` `Next`  '
    - '         '
    - '         '
```

**Comment by Arasple** [comment]
This is just how it works. Every layout of the menu should match a unique layout of PlayerInventory

**Comment by Tanguygab** [comment]
yeah but even with 
```yml
PlayerInventory:
  - - '         '
    - '  `Pre` `Welcome` `Next`  '
    - '         '
    - '         '
  - - '         '
    - '  `Pre` `Close` `Next`  '
    - '         '
    - '         '
``` 
it doesn't work
