### ISSUE TITLE
Trmenu 2 BETA 无法修改容器类型 无法监听文件保存

### ISSUE THREAD

**Issue by TUCAOEVER** [Arasple/TrMenu#109]
################################################################################
#
#  ____________________   _____  __________________   ____ ___
#\__    ___\______   \ /     \ \_   _____/\      \ |    |   \
#  |    |   |       _//  \ /  \ |    __)_ /   |   \|    |   /
#  |    |   |    |   /    Y    \|        /    |    |    |  /
#  |____|   |____|_  \____|__  /_______  \____|__  |______/
#                  \/        \/        \/        \/
#
# Example menu of TrMenu
#
# - TrMenu Docs：https://trmenu.trixey.cn
# - PlaceholderAPI: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
# - Custom Heads: https://minecraft-heads.com/custom-heads
#
################################################################################
# The inventory's title
Title:
  - '        &8▶ &8拍卖 &7| &8AUCTION &8◀'

# The update time of inventory's title (in ticks), Default: -1
Title-Update: -1

TYPE: HOPPER
# Defines the layout of this menu
# *(Each character represents a button)
Shape:
  - '  1  '

# Menu Options (All are optional)
Options:
  # (Default: true)
  Lock-Player-Inv: true
  # Use the arguments of an open command as variables (Var: {N*}) (Default: false)
  Transfer-Args: false
  # Each time when an icon updates, plugin refreshes the player's inventory
  # [!] Do not recommend. You should only enabled this when you require fast animations in lower Minecraft version
  Update-Inventory: false
  # Force the arguments it needs (Default: 0)
  Force-Transfer-Args: 0

# Buttons of this menu
# You can re-define ones' slots
Buttons:
  '#':
    # (Optional) The period for lore, materials and names to update (in ticks)
    update: -1
    # (Required) Default display part
    display:
      # Materials, or specify item
      mats: GRAY_STAINED_GLASS_PANE
      name:
        - ' '
      lore:
    # Click Actions
    actions:
      # ClickType - [Actions]
      all: ['sound: BLOCK_NOTE_BLOCK_PLING-1-1']
  '1':
    update: -1
    display:
      mats: 'BOOK'
      name:
        - '&7▶ &f如何将物品上架至拍卖行?'
      lore:
        - '&8&m                                        '
        - '&f第一步 选择物品&6➷'
        - ' &7&o将需要上架至拍卖行的物品'
        - ' &7&o放置于背包内'
        - ''
        - '&f第二步 上架拍卖&6➷'
        - ' &7&o取出任意数量的物品置于手中'
        - ' &7&o输入指令 &6&o"/auction start"'
        - ''
        - '&f第三步 调整拍卖信息&6➷'
        - ' &7&o输入指令后 系统会自动弹出调整界面'
        - ' &7&o分别会经历 &6&o调整数量 调整价格'
        - ' &6&o调整最低增幅价 调整时效 &7&o四个阶段'
        - ' &7&o通过界面内的按钮进行增减调整即可'
        - ' &7&o调整拍卖信息完成后 物品将上架至拍卖行'
        - '&8&m                                        '
        - '&7● &f点击此处以打开拍卖行菜单...'
    actions:
      all: ['sound: BLOCK_STONE_PRESSURE_PLATE_CLICK_ON-1-1']
      left:
        - 'command: auction'

配置如上所示 V1 版本完全正常 V2 版本无法监听文件保存 无法实时更新菜单

**Comment by Arasple** [comment]
BETA 版本暂未添加此项功能. 正式版会有
