### ISSUE TITLE
Menus do not appear or do not open and reload does not work.

### ISSUE THREAD

**Issue by RE4ERKA** [Arasple/TrMenu#121]
### After updating several of my plugins (about 10-20 plugins) and TrMenu itself from 1.21 to 1.22. This problem has occurred.
Server Core: _PaperSpigot (Paper-243)_
Server version: _1.14.4_
PlaceholderApi _2.10.8_
If I made a mistake anywhere, then I'm sorry to bother you. Thanks in advance if you fix this.

![image](https://user-images.githubusercontent.com/66727581/89132472-9acc7280-d53e-11ea-8c79-a45221a3570a.png)

**Comment by Tanguygab** [comment]
download the latest version of TrMenu (2.01) here
https://github.com/Arasple/TrMenu/actions
