### ISSUE TITLE
The offhand ''F'' key no longer works

### ISSUE THREAD

**Issue by Sikatsu** [Arasple/TrMenu#122]
Shortcuts:
  Offhand: []
  Sneaking-Offhand: []
  Right-Click-Player: []
  Sneaking-Right-Click-Player: []
  PlayerInventory-Border-Left: []
  PlayerInventory-Border-Right: []
  PlayerInventory-Border-Middle: []

I still can't use the F key anymore for the offhand despite the settings above. 
Seems like TrMenu blocks it from being used, even if not linked to a menu.

**Comment by Tanguygab** [comment]
I can confirm
