### ISSUE TITLE
BSTATS ERROR

### ISSUE THREAD

**Issue by ManuGooX** [Arasple/TrMenu#14]
Hello, I've got a problem with your plugin and I don't know if it's internal or if I have made something wrong. Could you help me?

Here you can see a picture about the error.

![image](https://user-images.githubusercontent.com/40543551/72466409-1fd97f80-37d9-11ea-916f-bd87dd57f2a4.png)

**Comment by Arasple** [comment]
Will be fixed in v1.12-R4
