### ISSUE TITLE
1.13 bugg with the 'tell:' actions

### ISSUE THREAD

**Issue by Teyir** [Arasple/TrMenu#19]
Hello, I have installed the last update 1.13, my servor is on 1.15.1 paper spigot and when I have installed the last update my tell actions don't work, before he work.

This is the line →  - 'tell: &d&l%player_name% vient d''améliorer sa limite de fours au LVL10<players>'

Thank you very much.

**Comment by Arasple** [comment]
It works fine with me, could you show me more details?
like your menu config

**Comment by Teyir** [comment]
This is my menu → https://pastebin.com/eR07cBrD

**Comment by Arasple** [comment]
I just re-uploaded a version, please try to use it to see if still has this issue

**Comment by Teyir** [comment]
I have the same problème → https://prnt.sc/qqnpfz → https://prnt.sc/qqnplh

**Comment by Arasple** [comment]
I still require more information since this issue can not be reproduced on my circumstances.
Please consider having a fresh reinstall of the latest version
