### ISSUE TITLE
I cannot reload trmenu with Catserver 1.6

### ISSUE THREAD

**Issue by cuifuyani** [Arasple/TrMenu#25]
I'm not sure whether the author of trmenu is Chinese or ... So i will write it bilingualy.
After I uploaded the new version of trmenu(1.6) into my server plugin file and tried to reload it, i confronted some errors, causing trmenu unable to reload. Here is the log of that error.
我刚升级我的trmenu完结果不能reload，这是错误报告。服务端：carserver
https://paste.ubuntu.com/p/T88352Yjvk/

**Comment by Arasple** [comment]
Fixed
