### ISSUE TITLE
json text in item NBT support request.

### ISSUE THREAD

**Issue by playbabe** [Arasple/TrMenu#27]
This is item NBT
`{HideFlags: 63, display: { Name: '[{"translate":"gui.learnbook.miner"},{"text":" "},"translate":"gui.learnbook.lore0"}]'}}`

but '/menu item' will get this result
`{"type":"IRON_PICKAXE","meta":{"display":{"Name":{"type":"STRING","data":"{\"text\":\"gui.learnbook.miner&f &fgui.learnbook.lore0\"}"}},"HideFlags":{"type":"INT","data":63},"Damage":{"type":"INT","data":0}}}`

edit for extra information*
It seem like  ' mats: - '<json>' ' doesn't accept nbt without `"type":"STRING","data":`

**Comment by Arasple** [comment]
A new way to use NBT tags has been added in the update of v1.18
