### ISSUE TITLE
在使用spigot参数 --plugins <dir> 无法加载...

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#29]
在使用spigot参数 --plugins <dir> 无法加载TrMenu，不知道是不是TabooLib的问题（在服务器启动时有TabooLib的错误）
参数来自: http://www.spigotmc.org/wiki/start-up-parameters/?noRedirect=1

**Comment by Arasple** [comment]
有报错就贴出来，以及你参数设置的值

**Comment by TSIXS** [comment]
> 有报错就贴出来，以及你参数设置的值

是Akarin的锅，已经过测试（连锁反应...）
