### ISSUE TITLE
TrMenu菜单问题

### ISSUE THREAD

**Issue by fyxrim** [Arasple/TrMenu#3]
- 1.12 版本中更新周期异常
- 捕获聊天完善

1.更新周期 你也知道吧 是我AkkLive
2.提议 捕获聊天
3.问题 刷新变量
如我现在菜单显示挖矿数 1 然后挖矿一个钻矿 然后菜单显示是1  我papi parse 变量是挖矿数2
4.提议 点击条件
经验exp 权限permission 金币vault 点券PlayerPoints
5.提议 玩家数量次数或全体玩家数量次数
如像一样道具商店  购买飞行只能限制1数量

**Comment by Arasple** [comment]
fixed
