### ISSUE TITLE
Commands with Arguments not working 1.15.2

### ISSUE THREAD

**Issue by razorrider7** [Arasple/TrMenu#31]
When I create a menu, and run the menu's command, such as "/xpbottler" it works, but adding arguments like "/xpbottler 5" makes the plugin not recognize the command, and I get an 'Unknown command. Type "/help" for help.' message.

**Comment by Arasple** [comment]
Did you set this to true in your menu configuration?
```YAML
Options:
  Transfer-Args: true
```
