### ISSUE TITLE
multiple Titles menus

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#32]
Hey, I've got an issue with this plugin.
When you have a menu that has 2 or more titles, and Title-Update, then the player will see his selected hotbar slot changed to the first empty slot.
For example, I have a diamond sword in my hand, then when I open the menu, I will have an empty slot (if there is) selected instead
![2020-02-12_15 24 56](https://user-images.githubusercontent.com/45695833/74343775-e2521d00-4dab-11ea-9eaa-7fed1d33d7d2.png)
![2020-02-12_15 25 02](https://user-images.githubusercontent.com/45695833/74343779-e41be080-4dab-11ea-98d3-3ff4dfa076c0.png)

I'm on 1.15.2 and haven't tested this in any other versions

**Comment by Arasple** [comment]
It is designed like this, for update title will cause player's hand item keep flashing
When player close the menu it will auto changed back to the slot before

However, I will make it optional in the next update

**Comment by Arasple** [comment]
Updated in v1.18
