### ISSUE TITLE
菜单有时候会出现频闪

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#36]
可能是我调整的菜单刷新率太高了？（3tick）,每当我保持在菜单页面的时候都会不间断出现频闪。不知道可不可以修复这个问题？

**Comment by Arasple** [comment]
你有使用动态标题吗

动态标题频闪这个问题我目前暂无解决方案，只有调高频率

**Comment by BackWheel** [comment]
> 你有使用动态标题吗
> 
> 动态标题频闪这个问题我目前暂无解决方案，只有调高频率

不是标题，而是菜单的整个界面。就时不时会闪一下

**Comment by Arasple** [comment]
我说错了，我的意思是**你有使用动态标题吗** ，目前已知频闪这个问题是由动态标题导致的

**Comment by BackWheel** [comment]
是的，我有使用。那么这个问题短期内会修复吗？

**Comment by BackWheel** [comment]
请问这个bug会修复吗?

**Comment by BackWheel** [comment]
@Arasple

**Comment by Arasple** [comment]
受原版所限，目前我无能为力
