### ISSUE TITLE
Javascript question

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#39]
Hello,

I am trying to make a news menu with auto-updates from instagram to inform my player the recent posts.

Do you think it is possible to do with javascript get some html elements from an url?

 I am trying to get only the post description and time with the instagram widget testing first with my computer:
https://pastebin.com/25P1QXxs
https://snapwidget.com/embed/772374.html

Trying to get description and time.(url
![Screenshot_2](https://user-images.githubusercontent.com/18188565/74591808-4fb7b500-501b-11ea-9645-e9797a6363fa.png)
)

But idk if is possible with TrMenu, thanks!

**Comment by Arasple** [comment]
I don't know, it can't just be done by TrMenu, only can achieve with custom plugin which processes such information and provide placeholders
