### ISSUE TITLE
动作部分问题

### ISSUE THREAD

**Issue by fyxrim** [Arasple/TrMenu#4]
actions:
          LEFT:
            - 'tell: &7&l[&8&l!&7&l] &7请按住 &6shift &7点击来确认购买，以免误操作'
            - 'close'
          SHIFT_LEFT:
            - 'console: cc give physical 秘境珍宝 1 %player_name%'

重载配置后
第一次点击后没问题  第二次不行了没反应

**Comment by Arasple** [comment]
fixed in v1.05
