### ISSUE TITLE
图标显示不正常

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#40]
https://i.loli.net/2020/02/16/XgFfx7rA9nQLWyB.png
https://i.loli.net/2020/02/16/XgFfx7rA9nQLWyB.png

不知道为何我这个按钮的lore会凭空出现

**Comment by BackWheel** [comment]
我有在另外一个按钮上的lore写[正在此页],可并非是我截图的那按钮...

**Comment by Arasple** [comment]
提供一下整个菜单的配置
`/trmenu share <id>`

**Comment by BackWheel** [comment]
https://hasteb.in/ritewepi

**Comment by BackWheel** [comment]
我尝试研究了一下这个问题，只有当带有玩家头颅的图标被加载之后会出现这种问题。当我使用原版玩家头颅（不加载玩家皮肤的）作为按钮的时候并没有这个问题

**Comment by Arasple** [comment]
已修复，重新下载即可
