### ISSUE TITLE
开启其他GUI有概率闪退

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#41]
当我使用TrMenu的按钮开启其他插件的GUI界面有概率会直接闪退

**Comment by BackWheel** [comment]
举个例子，我用菜单的按钮打开ShopGUIPlus插件的商店菜单，当我按下按钮之后商店会出现一瞬间然后就消失了

**Comment by Arasple** [comment]
请更新到最新版本

**Comment by BackWheel** [comment]
尝试安装你刚刚的新版本，还是有这个问题

**Comment by BackWheel** [comment]
这个问题不是百分百会出现，有时候会有时候不会

**Comment by BackWheel** [comment]
我貌似发现了问题所在，是因为菜单标题的刷新时间导致的，当我将刷新时间由3tick改为10tick就没出现这个问题了

**Comment by BackWheel** [comment]
可以确认的是问题所在就是标题的动态导致的，当我将标题改为静态之后问题就再没出现过。希望作者能够早日修复这个严重的问题awa

**Comment by Arasple** [comment]
Fixed in v1.19
