### ISSUE TITLE
无法正常显示玩家头颅材质

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#43]
当我创建一个按钮并且将他的材质设置为变量%player_name%的时候，大多时候材质无法正常显示（依旧是原版头颅）

**Comment by Arasple** [comment]
请提供菜单配置，服务端版本

**Comment by BackWheel** [comment]
https://hasteb.in/semuleje

服务端版本为:1.15.2(paper-112)

**Comment by Arasple** [comment]
后台是否有 HTTP 相关报错？

**Comment by BackWheel** [comment]
并没有

**Comment by Arasple** [comment]
fixed
