### ISSUE TITLE
Player skull metadata override

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#44]
当我在同一页菜单中出现两个以玩家头颅为材质的按钮（材质相同）时，当我将鼠标指针移动到其中一个图标上后等待一段时间，图标的标题有几率会瞬间闪烁另一个图标的标题

**Comment by BackWheel** [comment]
除此之外，如果在某个菜单存在上述的情况，当我打开另一个带有相同材质图标的菜单时，那个相同材质的图标lore会出错

**Comment by BackWheel** [comment]
例如我在这个菜单是我刚开始说到的同一页菜单出现的两个相同的按钮的那个菜单:（假设这个为菜单1）
https://hasteb.in/zalimovi
然后这个是另一个菜单，它拥有上面菜单中的一个相同图标:（假设这个为菜单2）
https://hasteb.in/catusiqo

当我打开菜单2的时候Lore出现错误，如图:https://i.loli.net/2020/02/17/83Y1iZ7PbNatzGE.png

**Comment by BackWheel** [comment]
从上面可以看到菜单2的图标并没有任何Lore,可是菜单1的Lore却凭空出现在菜单2的图标中

**Comment by Arasple** [comment]
Fixed in v1.19
