### ISSUE TITLE
新的动作建议:打开网址

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#45]
希望能够新增一个插件按钮动作，当玩家点下按钮的时候打开预设的网址。

**Comment by TSIXS** [comment]
我认为这个不太可能实现，因为打开URL是Chat中的操作，只能通过点击TextComponent消息才能进行

**Comment by BackWheel** [comment]
我也不太清楚，因为我本身不了解太多插件制作方面的问题，可以做到的话显然会让插件更加方便。(如果以后可以的话?)

**Comment by Arasple** [comment]
服务端不可能实现
你只能通过点击 JSON 消息或书本行来打开 URL

> 'tellraw: 点击 <这里?url=https://trmenu.trixey.cn> 打开wiki'
