### ISSUE TITLE
漏洞:开启菜单的所需权限貌似无效？

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#46]
当我给一个菜单设置开启所需的权限后，其他玩家已经可以正常打开菜单。不知道是我配置问题还是Bug?这个是我的菜单配置:https://hasteb.in/mamucici

**Comment by Arasple** [comment]
尝试开启 LuckPerms 的 verbose, 检测打开过程中的权限

配置没有问题

**Comment by BackWheel** [comment]
我检查了一下，这应该是我的问题
