### ISSUE TITLE
自动重载可能存在的隐患

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#49]
我注意到，在多次使用/trmenu reload后，对一些原有的已加载菜单进行编辑，保存后，一次刷出好几条：
- [TrMenu] INFO | 监听到文件改动并自动成功重载了菜单 xxx.yml
这样的消息，我担心菜单多起来，会出现很多不必要的CPU消耗

**Comment by Arasple** [comment]
Fixed in v1.19
