### ISSUE TITLE
最新版不兼容Yum

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Arasple/TrMenu#50]
当TrMenu和Yum并存时，Yum不加载。删除TrMenu后Yum加载正常。

并且TrMenu加载时间感觉变长了。
希望优化。

p.s. 尝试换过服务端核心，无用

**Comment by BackWheel** [comment]
说实在Yum本身就存在很多误报问题，个人认为如果你用Yum的侦测功能还不如使用服务端自带的timings。

**Comment by Arasple** [comment]
Fixed in v1.19
