### ISSUE TITLE
can't using action in shortcut feature

### ISSUE THREAD

**Issue by NightPrimez** [Arasple/TrMenu#53]
im trying to test it with
` SNEAKING-OFFHAND: 'op: say no'`
` SNEAKING-OFFHAND: op: say test`
or
```
SNEAKING-OFFHAND: 
  - 'op: say no'
```

but it's still not working

**Comment by Tanguygab** [comment]
Hey, to regroup suggestions related to commands, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/92) =)
Can you close this so we can keep the GitHub clean ? thanks =)
