### ISSUE TITLE
%player_name% Placeholder Broken

### ISSUE THREAD

**Issue by RageYT** [Arasple/TrMenu#59]
After installing the latest update, version 1.2, my placeholders for the menu have broke and it displays a default skin. I've restarted my server and left the server to see if it would fix it, but nothing changed.

### PaperSpigot Version
> 89-1.15.2
### PlaceholderAPI Version
> 2.10.5-DEV-85
### TrMenu Version
> 1.2

_The bottom-right corner of the GUI, that's what I mean_
![2020-03-02_19 26 17](https://user-images.githubusercontent.com/17907584/75730890-24d88c80-5cbc-11ea-8c5e-7b0718d361c0.png)

**Comment by Galaxy-VN** [comment]
try %player_displayname% ?

**Comment by Galaxy-VN** [comment]
but ye seem like 1.2 has broken it

**Comment by Galaxy-VN** [comment]
@Arasple

**Comment by Arasple** [comment]
Can you use `%player_name` in item's display name or lore?

**Comment by Galaxy-VN** [comment]
> Can you use `%player_name` in item's display name or lore?

i have test it's broken in head lore and name still fine

**Comment by Arasple** [comment]
fixed in v1.21
