### ISSUE TITLE
1.8.8 Crash

### ISSUE THREAD

**Issue by Galaxy-VN** [Arasple/TrMenu#60]
Plugin version 1.21
Server version 1.8.8
Logs: [latest.log](https://github.com/Arasple/TrMenu/files/4302105/latest.log)
Crash logs: https://pastebin.com/zbGM9ega
Trmenu crash on 1.8.8

**Comment by Galaxy-VN** [comment]
@Arasple

**Comment by AzureHanChen** [comment]
同样遇到该问题 (Tr全系插件均有该BUG)
Spigot和Paper的最终构建
crash logs文件
https://paste.ubuntu.com/p/gH3rfmpSkD/
(三款Tr插件均为截至回复时最新版)

**Comment by Arasple** [comment]
Confirmed to be a new TabooLib bug, will be fixed

**Comment by Arasple** [comment]
Fixed, use the command to update your TabooLib

`/libupdate`
