### ISSUE TITLE
Arguments in materials + set default shape

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#62]
Hey, when doing my shop menu, I encountered a problem while trying to display an item.
I setted my 2nd argumeny (so I used {1} ) as "apple", then I used it in my item display name. 
From this point, everything works.

But then, I tried to place the argument in my item material (`mats: "{1}"`,`mats: {1}, heck I've even tried with json: `mats: "{"type":"{1}"}"`}` Nothing worked. I tried replacing {1} by apple and it worked, it just doesn't when I set the argument instead....

Also, I'd like to suggest a new option for menus that would let us be able to set the default shape.
I've already tried to put `set-shape; <shapenumber>` in `open-actions:` but it didn't work.

**Comment by Arasple** [comment]
Hello,
if you want use placehoders or arguments for item material, just add `<variable>` tag
```YAML
  material: '{0}<variable>'
```

The default page feature will be considered.

**Comment by Tanguygab** [comment]
> Hello,
> if you want use placehoders or arguments for item material, just add `<variable>` tag
> 
> ```yaml
>   material: '{0}<variable>'
> ```
Just a suggestion to help others, you should add it here : https://trmenu.trixey.cn/menu/button/icon/display/material
