### ISSUE TITLE
I can't add more than one ActionCatcher at same time

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#69]
Hi!
I would love to see a Catcher system more complete:

- Possibility to add more than one "ActionCatcher" inside of one(To do surveys, quests, etc.).
- Possibility to obtain all the written inputs from the player, to use then in the next Catchers.

**Comment by Tanguygab** [comment]
Hey, to regroup all suggestions about the Input Catcher, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/93) =)
Can you close this so we can keep the GitHub clean ? thanks =)
