### ISSUE TITLE
PlaceHolderApi in Skulls not working

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#71]
Hi, I need to use a placeholder from papi in:

`     mats:
        - '<skull:%X%>'`

I investigate the code, and the problem is there isn't a "Vars.replace" there.:

```
       if (this.option == Option.TEXTURE_SKULL) {
            this.staticItem = Skulls.getCustomSkull(this.optionValue);
            return this.staticItem.clone();
        }
        if (this.option == Option.HEAD) {
            return Skulls.getPlayerSkull(Vars.replace(player, this.optionValue)).clone();
        }

```
I was trying the <variable> to many formats, and no works.

**Comment by Arasple** [comment]
Yes, currently custom texture skull do not support placeholders

**Comment by Arasple** [comment]
will be supported in v2
