### ISSUE TITLE
InputCatcher Problem

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#72]
Hi, I can't use in <Before=X>(InputCatcher Action) the action "TITLE:<TITLE=X><SUBTITLE=X>"

How can I use it?

**Comment by Ismael-GT** [comment]
Also the json

**Comment by Ismael-GT** [comment]
Another problem inside of <require=X>

I can't use: <Require=%TrMenu_TaPapi_$input|{{player_has_played_before}%>
The console give an error for this char  '|'

**Comment by Tanguygab** [comment]
you put 2 { there `{{player_has_played_before}`

**Comment by Tanguygab** [comment]
Hey, to regroup all suggestions about the Input Catcher, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/93) =)
Can you close this so we can keep the GitHub clean ? thanks =)
