### ISSUE TITLE
Command /trmenu Open

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#73]
Hi,

I need to add variables when I force the player open a menu from **console**, like:
"/trmenu open <name_menu> <player_name> 1 25 90"

Thanks!

**Comment by Tanguygab** [comment]
Hey, to regroup all suggestions about arguments, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/91) =)
Can you close this so we can keep the GitHub clean ? thanks =)

**Comment by Arasple** [comment]
will be supported in [v2](https://github.com/Arasple/TrMenu/blob/v2/src/main/kotlin/me/arasple/mc/trmenu/commands/sub/CommandOpenMenu.kt) :)
