### ISSUE TITLE
Bug open-actions AND Close-Actions

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenu#78]
The action wait and delay inside of "Open-Actions:" and "Close-Actions" doesn't works:

  - 'wait: 100'
OR
  - 'delay: 100'

**Comment by Tanguygab** [comment]
Actually, I tested and it does work, BUT it doesn't with the set-shape action (I think)

**Comment by Ismael-GT** [comment]
> Actually, I tested and it does work, BUT it doesn't with the set-shape action (I think)

Thats true, wait works with <wait:100> in the end of some action.

set-shape doesn't works, arasple need to check it

**Comment by Tanguygab** [comment]
you can close again this issue because I've already report it there https://github.com/Arasple/TrMenu/issues/63#issuecomment-597655666
