### ISSUE TITLE
Errors with TrMenu and TabooLib after update

### ISSUE THREAD

**Issue by maxito43** [Arasple/TrMenu#82]
It's showing console errors for me after I updated TRmenu from 1.15 to 1.21.
Running latest paper build 185.

It shows the errors with every executed server command. The menu's itself work fine.

https://pastebin.com/XKjrTrJS

**Comment by Tanguygab** [comment]
try to delete TabooLib's folder

**Comment by maxito43** [comment]
I've tried, it regenerated the folder and redownloaded the jars, but the errors are still there.

In fact server just crashed for the first time due to Java error, so it seems to be getting worse.
First thing I see is TabooLib: https://pastebin.com/704hyRva

**Comment by maxito43** [comment]
Rolling back to TRMenu 1.15, and deleting the TabooLib folder doesn't help either.

**Comment by Tanguygab** [comment]
then maybe try to delete the libs folder in your server folder, and again the TabooLib folder in your plugins folder

**Comment by maxito43** [comment]
Ah! I haven't seen that one, I will try next reboot

**Comment by Tanguygab** [comment]
Any news ?

**Comment by maxito43** [comment]
I've deleted the libs folder, Taboolib folder but the error is still there

**Comment by Tanguygab** [comment]
What's your server version ? (also, can you come on Discord as it is easier to talk there ? x))

**Comment by Tanguygab** [comment]
did we fix this ? I don't remember x)
