### ISSUE TITLE
Add condition support in lore section

### ISSUE THREAD

**Issue by BukkitProfi** [Arasple/TrMenu#85]
Example:
![image](https://user-images.githubusercontent.com/64229180/80315962-73b22680-8814-11ea-8d0d-41240ce8c140.png)

**Comment by Tanguygab** [comment]
If I remember correctly, this will be a thing in TrMenuPro, I don't know if it will make it in the free version

**Comment by Arasple** [comment]
will be supported in v2

https://github.com/Arasple/TrMenu/blob/v2/src/main/kotlin/me/arasple/mc/trmenu/display/item/Lore.kt
