### ISSUE TITLE
Open-Actions issue with Shapes

### ISSUE THREAD

**Issue by Tomi010817** [Arasple/TrMenu#88]
### Description:
When you set a sound for when opening and closing a menu, the sound for closing the menu runs when closing other shapes that are not the first one, but when you change of shape, the sound for opening the menu won't run again, and it is a little bit confusing. 
EDIT: It will also happen with open-actions when changing from other shapes to the first one, running them again.

### Expected Behavior:
To not run the sound when closing the menu, when you aren't on the first shape. And only play the close-actions when you are on the first shape. Tho I actually undestand the logistic of it (that open and close actions work with shapes altogether).

### My Suggestion:
I know that my expected behavior can be also a little confusing, so here I bring my opinion/suggestion to get it much less confusing and useful for the plugin:
- Add the option to set Open-Actions and Close-Actions to each shape.

 **Complete example of how it would work (with explanation):
 https://hastebin.com/kegacoyiha.bash
 Another example:
 https://hastebin.com/sehugayuvu.http**

**Comment by Tanguygab** [comment]
Hey, regroup all suggestions about shapes, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/90) =)
Can you close this so we can keep the GitHub clean ? thanks =)
