### ISSUE TITLE
Title for each Shape [Suggestion]

### ISSUE THREAD

**Issue by Tomi010817** [Arasple/TrMenu#89]
### Description:
As the title says, it would be a very great and useful feature to be able to put a title on each shape of a menu. I know that a way to handle this is with 'set-args' and title-update, but there is an annoying twinckle that happens when you set the title to update in an interval of ticks, and comes to be more annoying when reading lores of buttons. So, this feature would save us from that situation since we will be able to use it and only get the title updated when changing of shape.

 **An example of how it would work:
 https://hastebin.com/mazituleso.bash**

**Comment by Tanguygab** [comment]
Hey, regroup all suggestions about shapes, I created [one containing all suggestions](https://github.com/Arasple/TrMenu/issues/90) =)
Can you close this so we can keep the GitHub clean ? thanks =)
