### ISSUE TITLE
Shapes Suggestions

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#90]
Hey, I wanted to share and regroup together some suggestions about shapes that I had in mind, aswell as other people:
 - - [ ] Categories of Shapes, or just Sub-Shapes, idk how that would look x)
 - - [x] Default-Shape, so you can open a menu with at defined shape
 - - [x] /trmenu open <menu> -s:# where # is a number that lets you open a menu at a specific shape, overrides the default shape
 - - [x] set-shape working inside open-actions and Input Catcher as asked [here](https://github.com/Arasple/TrMenu/issues/63)
 - - [x] different titles for each shapes as asked [here](https://github.com/Arasple/TrMenu/issues/89)
(**EDIT:** Actually, not really necessary as we already have the `set-title` action)
 - - [ ] save displayed shape when auto-reload or /trmenu reload
 - - [x] instead of using the open-actions, create per-shapes open actions as asked [here](https://github.com/Arasple/TrMenu/issues/88)  

I'll try later to get some examples of how it would look, I'll also create another issue regrouping every suggestions about arguments

**Comment by Tomi010817** [comment]
+1 Vote for this!

**Comment by Tomi010817** [comment]
😮

**Comment by Tanguygab** [comment]
Arasple's on fire x)
