### ISSUE TITLE
Major Problem with refreshing icons

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#94]
Hey, today it isn't a suggestion but a bug report that I'm posting.
So what's that bug ?
Well, when you have multiples icons with `refresh #`, they will sometimes appear in the wrong slots, or their properties will mix together (like, material from item 1 on item 2 and name from item 2 on item 1)
I consider this bug as major as this is one of the main features of TrMenu and also the reason why people would use it over others plugins such as ChestCommands or DeluxeMenus.

I can't really provide a video of the bug right now but I'll try later.

Also, I don't know why, but in some menus, it seems to work well, for example my Daily Rewards menu that I shared on the TrPlugins discord. I think it's because the inventory isn't full, and that there are still empty slots. if it isn't because of that, then idk, it may be random

**Comment by Arasple** [comment]
Thank you for your report :)
