### ISSUE TITLE
Add support to SkinRestorer

### ISSUE THREAD

**Issue by Shaarper** [Arasple/TrMenu#95]
Hello, I have a suggestion to add support for the SkinRestorer plug-in!
Without it, many heads are not displayed, because the player does not use the license. And replaces the skin with another one using the SkinRestorer plug-in.
For example, with 
mat: '<skinrestorer:PlayerHere>'

**Comment by Tanguygab** [comment]
Another idea of syntax would be like the other ones for heads and skulls:
<skinrestorer:PlayerName> and it will get the player's skin attributed through SkinRestorer. If no skin were given to the player through SkinRestorer, his normal MC skin will be displayed instead.
Also, it could be used to get a the head from a skin file from SR, like this `<skinrestorer:FileName.skin>`
