### ISSUE TITLE
Add automatic translation to the menu

### ISSUE THREAD

**Issue by Shaarper** [Arasple/TrMenu#97]
**Hello**, would you like to see automatic translation in the menu?
For example, I have made a menu where you can select a configuration to change the **language**.
And there will be different languages (List).
Choosing changes the configuration (text) of the menu for its chosen **language**. 

That would be very cool for your menu.
Even if you need to make separate menus for each **language**.

**Comment by Arasple** [comment]
It is possible to make in v2
