### ISSUE TITLE
SHORTCUT-OPEN BUG

### ISSUE THREAD

**Issue by DarkFort** [Arasple/TrMenu#98]
The SHORTCUT-OPEN parameter opens a menu when a player is clicked, although it is disabled.
![image](https://user-images.githubusercontent.com/25278617/85950486-af2cb680-b965-11ea-9f52-6f6bc1972191.png)
![image](https://user-images.githubusercontent.com/25278617/85950493-b9e74b80-b965-11ea-9f56-1777ec25c1b4.png)

**Comment by Arasple** [comment]
Will be fixed in v2
